diary 'sourcedata/eeg/sub-s01.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
system('mkdir -p sub-s01/eeg');
eeg_init({'sourcedata/eeg/IC_trn_P01_F_1.bdf', ...
          'sourcedata/eeg/IC_trn_P01_F_2.bdf', ...
          'sourcedata/eeg/IC_trn_P01_f_3.bdf', ...
          'sourcedata/eeg/IC_trn_P01_f_4.bdf', ...
          'sourcedata/eeg/IC_trn_P01_O_1.bdf', ...
          'sourcedata/eeg/IC_trn_P01_O_2.bdf', ...
          'sourcedata/eeg/IC_trn_P01_O_3.bdf', ...
          'sourcedata/eeg/IC_trn_P01_O_4.bdf'}, ...
          'sub-s01/eeg/sub-s01_task-faceFO_eeg.set');
         
diary 'sourcedata/eeg/sub-s02.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
system('mkdir -p sub-s02/eeg');
eeg_init({'sourcedata/eeg/IC_trn_P02_F_1.bdf', ...
          'sourcedata/eeg/IC_trn_P02_F_2.bdf', ...
          'sourcedata/eeg/IC_trn_P02_F_3.bdf', ...
          'sourcedata/eeg/IC_trn_P02_F_4.bdf', ...
          'sourcedata/eeg/IC_trn_P02_O_1.bdf', ...
          'sourcedata/eeg/IC_trn_P02_O_2.bdf', ...
          'sourcedata/eeg/IC_trn_P02_O_3.bdf', ...
          'sourcedata/eeg/IC_trn_P02_O_4.bdf'}, ...
          'sub-s02/eeg/sub-s02_task-faceFO_eeg.set');

diary 'sourcedata/eeg/sub-s03.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
system('mkdir -p sub-s03/eeg');
eeg_init({'sourcedata/eeg/IC_trn_P03_F_1.bdf', ...
          'sourcedata/eeg/IC_trn_P03_F_2.bdf', ...
          'sourcedata/eeg/IC_trn_P03_F_3.bdf', ...
          'sourcedata/eeg/IC_trn_P03_F_4.bdf', ...
          'sourcedata/eeg/IC_trn_P03_O_1.bdf', ...
          'sourcedata/eeg/IC_trn_P03_O_2.bdf', ...
          'sourcedata/eeg/IC_trn_P03_O_3.bdf', ...
          'sourcedata/eeg/IC_trn_P03_O_4.bdf'}, ...
          'sub-s03/eeg/sub-s03_task-faceFO_eeg.set');


